netflix:
  history_file: data/nf_history.csv
youtube:
  api_key: AIzaSyCF6T7hxRkfUv0C3ba-aDsOEm8MUJB_fEM
  history_file: data/yt_history.html
  cat_file: data/cats.json
  simulate_offset: 45
  simulated: true
database:
  name: data/mydb.db
log:
  filename: data/log/etl.log